apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-exporter
  namespace: watcher
  labels:
    app: squid-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid-exporter
  template:
    metadata:
      labels:
        app: squid-exporter
    spec:
      containers:
      - name: squid-exporter
        image: boynux/squid-exporter:latest
        env:
          - name: SQUID_EXPORTER_LISTEN
            value: ":9308"
          - name: SQUID_HOSTNAME
            value: "jcode-router-svc.watcher.svc.cluster.local"
          - name: SQUID_PORT
            value: "3000"
          # - name: SQUID_LOGIN
          #   value: "your_username"
          # - name: SQUID_PASSWORD
          #   value: "your_password"
        ports:
        - containerPort: 9308
---
apiVersion: v1
kind: Service
metadata:
  name: squid-exporter-svc
  namespace: watcher
  labels:
    app: squid-exporter
spec:
  selector:
    app: squid-exporter
  ports:
  - name: metrics
    port: 9308
    targetPort: 9308
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: squid-exporter-monitor
  namespace: watcher
  labels:
    app: squid-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: squid-exporter
  namespaceSelector:
    matchNames:
      - watcher
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s